name: ci-action
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
env:
  APP_NAME: my-app
  APP_VERSION: 1.0.0
jobs:
  CI-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the docker image
        run: docker build -t "$APP_NAME:$APP_VERSION" .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        run: docker push "$APP_NAME:$APP_VERSION"

      - name: Run tests
        run: echo "Running tests"
      - name: Deploy
        run: echo "Deploying"
